# site title
title: 拿枪的剑客

# user name or organization name
user: flcker

# issue repository
repository: blog

# multi-author
authors:

# token
# token should be separated by '#'
# example: 5#c31bffc137f44faf7efc4a84da827g7ca2cfeaa
token: 5#bf32aa6471b71c448a90893245f312e7dd34471

# posts per page
perpage: 10


# advance config

# organization repository (?)
organization: false

# post order
# order by create time" or "update time"
# 'UPDATED_AT' or 'CREATED_AT'
order: 'CREATED_AT'
